name: Laura
favicon: null
layout_spectrum: 0.88499
typography_spectrum: 0.11398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefff1'
    - '#56b08c'
    - '#fe4153'
    - '#fc7b15'
    - '#263d45'
  brandStrength: 0.875
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
